{
ActivityPlanningElement: "Activité - Avancement",
addNewCustomField: "ajouter un nouveau champ",
attributeCalculated: "est calculé (valeur par défaut calculée et champ en lecture seule)",
attributeDefault: "a une valeur par défaut",
attributeDoNotAutoFill: "ne pas pré-remplir",
attributeHidden: "masqué",
attributeNobr:"suivant sur même ligne",
attributeReadonly: "lecture&nbsp;seule",
attributeRequired: "obligatoire",
attributeUnique: "unique",
captionStyling: "style du libellé",
colFont: "police",
colFontSize: "taille de police",
colPreview: "aperçu",
confirmDeleteCustomField: "Confirmer la suppression du champ '${1}'.<br/><br/><b>ATTENTION<br/>Toutes les données contenues dans cette colonne seront définitivement perdues.</b>",
confirmDeleteCustomList: "Confirmer la suppression de la liste '${1}'.<br/><br/><b>ATTENTION<br/>Toutes les données de cette liste seront définitivement perdues.",
confirmResetCustomScreen: "Confirmer la suppression de la customisation pour cet écran.<br/>Ceci effacera toutes vos modification sur cet écran et supprimera vos champs personnalisés avec leurs données.",
currentValue: "valeur actuelle",
customListClass: "classe de la liste",
customListClassHelp: "C'est le nom pour la nouvelle classe d'objet de votre liste.<br/>Ce nom ne doit contenir que les caractères alphabétiques (sans espace) et commencer par une majuscule.<br/>Exemple &#58; <i> MaListe</i><br/>Vous ferez référence à cette liste en créant un champ nommé 'idClass' (dans l'exemple '<i>idMaListe</i>')",
customListName: "nom de la liste",
customListNameHelp: "C'est le nom en clair de la liste tel qu'il apparaitra dans l'écran d'édition de la liste",
dialogAddCustomList: "Ajouter une liste personnalisée",
dialogEditField: "Editer le champ",
editCustomLists: "Editer les listes personnalisées",
editCustomListsBack: "Retourner à la personnalisation des écrans",
editCustomListDelete: "Supprimer la liste personnalisée sélectionnée",
editCustomListSelect: "Sélectionner la liste à éditer",
editCusmtomListNew: "Créer une nouvelle liste personnalisée",
errorAlreadyDefinedName: "Vous avez specifié un nom de champ mais il existe déjà le libellé '${2}' attribué au nom du champ '${1}'. Veuillez effacer ce nom de champ<br/><br/>(Le plugin 'traductions personalisées' vous permet de modifier un libellé existant)<br/>",
errorCopyFile: "Erreur de copie du fichier ${1} vers ${2} <br/>Vérifiez les droits d'accès sur le répertoire ${3}",
errorDeleteFile: "Erreur de suppression du fichier ${1}<br/>Vérifiez les droits d'accès sur ce fichier",
errorDbformatInt: "'${1}' n'est pas une longueur pour un 'int'.<br/>La valeur doit être numérique, >1 et <=255", 
errorDbformatDecimal: "'${1}' n'est pas une longueur pour un 'decimal' ou 'numeric'.<br/>La valeur doit être 2 nombres séparés par une virgule&#44; le premier <=65 et le second <=30",
errorDbformatExisting: "Ce champ existe déjà en base avec un format '${1}' different de '${2}'.<br/>Veuillez selectionner le format existant pour réutiliser ce champ.",
errorDbformatVarchar: "'${1}' n'est pas une longueur pour un 'varchar'.<br/>La valeur doit être numérique et <=4000",
errorFieldNameFormat: "'${1}' n'est pas un nom de champ valide.<br/>Saisissez uniquement des caractères alphabétiques sans espaces.<br/>Le premier caractère doit être une lettre minuscule.",
errorInvalidEvaluationString: "L'expression<br/>&nbsp;&nbsp;&nbsp;${1}<br/>n'est par une instruction PHP valide ou contient un des mots clés interdits <br/>(${2})",
errorInvalidFormat: "La valeur '${1}' n'est pas valide pour le format '${2}'",
errorKeyword: "Le nom '${1}' est un mot réservé quue vous ne pouvez pas utiliser comme nom de champ",
errorListClassExists: "'${1}' est un nom de classe existant.<br/>Utilisez un autre nom pour votre liste.",
errorListClassFormat: "'${1}' n'est pas un nom valide.<br/>N'utilisez que des caractères alphanumériques sans espace.",
errorListClassNotExists: "'${1}' n'est pas un nom de liste existant.<br/>Vérifiez votre sélection.",
errorListClassKeyword: "'${1}' est un mot-clé réservé de PHP.<br/>N'utilisez pas de mot-clé réservé PHP <br/>${2}",
errorListClassReferenced: "'${1}' est utilisée par les objets suivants ${2}.<br/>Supprimer ces références avant de supprimer la liste.",
errorNewFieldDuplicate: "Le champ '${1}' existe déjà pour l'élément ${2} (mais il et peut-être masqué).<br/>Choisissez un autre nom de champ.",
errorReadFile: "Erreur de lecture du fichier ${1}<br/>Vérifiez que ce fichier existe bien",
errorReferenceFormat: "Erreur de format<br/>Le nom de ce champ '${1}' induit un format 'reference' car il commence par 'id' puis une majuscule",
errorReferenceNonExistingClass: "Erreur de format<br/>Le champ '${1}' fait implicitement référence à une classe '${2}' qui n'existe pas.",
errorUndefinedName: "Vous n'avez pas specifié de nom de champ et il n'existe pas de nom déjà existant pour le champ '${1}'.<br/>Veuillez renseigner un nom de champ",
errorWriteDatabase: "${1} erreurs lors de la mise à jour de la base de données.<br/>Consulter le fichier de logs pour plus de détail.",
errorWriteFile : "Erreur d'écriture du fichier ${1}<br/>Vérifiez les droits d'accès sur ce fichier",
fieldDbName: "nom du champ en base",
fieldFormat: "format",
fieldId: "nom du champ",
fieldLength: "longueur",
fieldName: "libellé du champ",
fieldPlaceAfter: "placer après le champ",
fieldStyling: "style du champ",
fieldValue:"valeur du champ",
fieldWithlibOnSameLine:"une description suit ce champ",
fixCustoRetry:"Rafraichissez cet écran (resélectionner le menu) tant que ce message s'affiche",
hideFieldsForProfile: "Attributs des champs pour un profil donné",
hideFieldsForStatus: "Attributs des champs pour un état donné",
hideFieldsForType: "Attributs des champs pour un type donné",
MeetingPlanningElement: "Réunion - Avancement",
menuScreenCustomization: "Personnalisation des écrans",
menuScreenCustomizationEditList: "Listes personnalisées",
messageCustomListOK: "Liste '${1}' correctement crée.",
messageCustomListDeleteOK: "Liste '${1}' correctement supprimée.",
messageScreenCustomizationERROR: "Erreur lors de la sauvegarde de cette modification",
messageScreenCustomizationNO_CHANGE: "Aucune modification à sauver pour ce champ",
messageScreenCustomizationOK: "Modifications du champ correctement prise en compte",
messageScreenCustomizationReopen: "Fermer ce message pour réouvrir la fenêtre d'édition du champ",
messageScreenCustomizationResetOK: "Ecran correctement réinitialisé à son état standard",
MilestonePlanningElement: "Jalon - Avancement",
newValue: "nouvelle valeur",
OrganizationBudgetElement: "Organisation - Budget",
ProjectPlanningElement: "Projet - Avancement",
resetCustomScreen: "effacer la customisation de cet écran",
sectionDefaultStatusClosed: "section fermée par défaut",
sectionStyling:"attributs visuels",
TestSessionPlanningElement: "Session de test - Avancement",
TicketSimple: "Ticket (simple)",
WorkElement: "Ticket - Travail",
}
