{
ActivityPlanningElement: "Activity - Progress",
addNewCustomField: "add new custom field",
attributeCalculated: "is calculated (default value calculated on readonly field)",
attributeDefault: "has default value",
attributeDoNotAutoFill: "do not auto fill",
attributeHidden: "hidden",
attributeNobr:"next on same line",
attributeReadonly: "read&nbsp;only",
attributeRequired: "required",
attributeUnique: "unique",
captionStyling: "style for caption",
colFont: "font",
colFontSize: "font size",
colPreview: "preview",
confirmDeleteCustomField: "Confirm deletion of field '${1}'.<br/><br/><b>ATTENTION<br/>Data stored on this column will be lost.</b>",
confirmDeleteCustomList: "Confirm deletion of the custom list '${1}'.<br/><br/><b>ATTENTION<br/>Data stored for this list will be lost.",
confirmResetCustomScreen: "Confirm reset screen to standard disposition.<br/>This will erase every change you made and delete your custom fileds with their data.",
currentValue: "actual value",
customListClass: "class of the list",
customListClassHelp: "It is the name of the new object class for your custom list.<br/>This name must containt only alphabetic characters (without spaces) and must start with an uppercase.<br/>Example &#58; <i> MyList</i><br/>You will refer to this list creating a field named 'idClass' (in the example '<i>idMyList</i>')",
customListName: "name of the list",
customListNameHelp: "It is the name of the list as it will be displayed in edition screen for the list",
dialogAddCustomList: "Add new custom list",
dialogEditField: "Edit field",
editCustomLists: "Edit custom lists",
editCustomListsBack: "Back to screen customization",
editCustomListDelete: "Delete selected custom list",
editCustomListSelect: "Select list to edit",
editCusmtomListNew: "Create a new custom list",
errorAlreadyDefinedName: "You have entered a name for this field but caption '${2}' already exists for field '${1}'. Please clear field name<br/><br/>You should use the plug-in 'custom translations' to change an existing caption)<br/>",
errorDeleteFile: "Error while deleting file ${1}<br/>Please check access rights to this file",
errorFieldNameFormat: "'${1}' is not a valid field name.<br/>Please use only alphabetic characters without spaces.<br/>First character must be a lowercase letter.",
errorCopyFile: "Error while copying file ${1} to ${2} <br/>Please check acces rights to directory ${3}",
errorDbformatInt: "'${1}' is not a valid length for an 'int'.<br/>Value must be numeric, >1 and <=255", 
errorDbformatDecimal: "'${1}' is not a valid length for a 'decimal' or 'numeric'.<br/>Value must be 2 numerics separated with a comma&#44; first <=65 and second <=30",
errorDbformatExisting: "This database field already exists with format '${1}' different from '${2}'.<br/>Please select existing format to reuse this field.",
errorDbformatVarchar: "'${1}' is not a valid length for a 'varchar'.<br/>Value must be numeric and <=4000",
errorInvalidEvaluationString: "The expression<br/>&nbsp;&nbsp;&nbsp;${1}<br/>is not a valid PHP instruction or contains one of the forbidden key words <br/>(${2})",
errorInvalidFormat: "The value '${1}' is not valid for format '${2}'",
errorKeyword: "Name '${1}' is a reserved key work that you cannot use as field name",
errorListClassExists: "'${1}' is an already existing class name.<br/>Please use another name for your custom list.",
errorListClassFormat: "'${1}' is not a valid name.<br/>Please use only alphabetic characters without spaces.",
errorListClassNotExists: "'${1}' is not an existing custom list name.<br/>Please check your selection.",
errorListClassKeyword: "'${1}' is a PHP reserved key word.<br/>Never use a PHP reserved key word <br/>${2}",
errorListClassReferenced: "'${1}' is used by following objects ${2}.<br/>Please delete corresponding references before deleting the list.",
errorNewFieldDuplicate: "The field '${1}' already exists for item ${2} (but can be hidden).<br/>Choose another name for the field.",
errorReadFile: "Error while reading file ${1}<br/>Please check that the file exists",
errorReferenceFormat: "Error on format<br/>The name of the field '${1}' expects a format 'reference' because it starts with 'id' followed by an uppercase",
errorReferenceNonExistingClass: "Error on format<br/>The field '${1}' implicitely references class '${2}' which does not exist.",
errorUndefinedName: "You did not enter a caption and no default caption exists for the field '${1}'.<br/>Please enter a caption",
errorWriteDatabase: "${1} errors during database update.<br/>Look at log file for more detail.",
errorWriteFile : "Error while writing file ${1}<br/>Please check access rights to this file",
evlMsg:"xTxhxixsx xixsx xaxnx xexvxaxlxuxaxtxixoxnx xvxexrxsxixoxnx<xbxrx/x>xDxoxnx'xtx xfxoxrxgxextx xtxox xbxuxyx xyxoxuxrx xvxexrxsxixoxnx.",
fieldDbName: "field name in database",
fieldFormat: "format",
fieldId: "name of the field",
fieldLength: "length",
fieldName: "caption for the field",
fieldPlaceAfter: "place after field",
fieldStyling: "style for field",
fieldValue:"value of the field",
fieldWithlibOnSameLine:"a description follows this field",
fixCustoRetry:"Refresh this screen (reselect menu) as long as this message is displayed",
hideFieldsForProfile: "Change fields attributes for a given profile",
hideFieldsForStatus: "Change fields attributes for a given status",
hideFieldsForType: "Change fields attributes for a given type",
MeetingPlanningElement: "Meeting - Progress",
menuScreenCustomization: "Screens customization",
menuScreenCustomizationEditList: "Custom lists",
messageCustomListOK: "List '${1}' created.",
messageCustomListDeleteOK: "List '${1}' deleted.",
messageScreenCustomizationERROR: "Error while saving this change",
messageScreenCustomizationNO_CHANGE: "No change to save for this field",
messageScreenCustomizationOK: "Changes correctly saved for this field",
messageScreenCustomizationReopen: "Close this message to open edition pop-up for the field",
messageScreenCustomizationResetOK: "Screen correctly reset to standard status",
MilestonePlanningElement: "Milestone - Progress",
newValue: "new value",
OrganizationBudgetElement: "Organization - Budget",
ProjectPlanningElement: "Project - Progress",
resetCustomScreen: "reset screen to standard disposition",
sectionDefaultStatusClosed: "section closed by default",
sectionStyling:"visual attributes",
TestSessionPlanningElement: "Test session - Progress",
TicketSimple: "Ticket (simple)",
WorkElement: "Ticket - Work",
}